import { NextResponse } from 'next/server';
import { Resend } from 'resend';

export async function POST(req: Request) {
    try {
        const body = await req.json();

        // Support both field naming conventions for backward compatibility
        const recipientEmail = body.email || body.to;
        const pdfData = body.pdfBase64 || body.pdfBuffer;
        const { subject, filename, clientName, message, businessName } = body;

        if (!process.env.RESEND_API_KEY) {
            // Fallback to mailto: if no API key
            const mailtoUrl = `mailto:${recipientEmail}?subject=${encodeURIComponent(subject || 'Your Estimate')}&body=${encodeURIComponent(message || 'Please find attached your estimate.')}`;
            return NextResponse.json({
                method: 'mailto',
                mailtoUrl,
                message: 'No email service configured. Opening email client.'
            });
        }

        const resend = new Resend(process.env.RESEND_API_KEY);

        if (!recipientEmail || !pdfData) {
            return NextResponse.json({ error: 'Missing required fields: email and PDF data' }, { status: 400 });
        }

        const buffer = Buffer.from(pdfData, 'base64');

        // Build HTML email with custom message
        const htmlContent = `
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
                <h1 style="color: #2563EB;">Estimate from ${businessName || 'SnapQuote'}</h1>
                <p>Dear ${clientName || 'Valued Customer'},</p>
                ${message ? `<p style="white-space: pre-line;">${message}</p>` : '<p>Please find attached your estimate.</p>'}
                <hr style="border: 1px solid #e5e7eb; margin: 20px 0;" />
                <p style="color: #6b7280; font-size: 12px;">
                    This estimate was generated by SnapQuote - Trade-Focused AI Estimator
                </p>
            </div>
        `;

        const data = await resend.emails.send({
            from: 'SnapQuote <onboarding@resend.dev>', // Update with verified domain later
            to: [recipientEmail],
            subject: subject || 'Your Estimate from SnapQuote',
            html: htmlContent,
            attachments: [
                {
                    filename: filename || 'Estimate.pdf',
                    content: buffer,
                },
            ],
        });

        return NextResponse.json({ success: true, data });
    } catch (error) {
        console.error('Email send error:', error);
        return NextResponse.json({ error: 'Failed to send email' }, { status: 500 });
    }
}
