import assert from 'node:assert/strict'
import { beforeEach, describe, test } from 'node:test'

import { POST as generateEstimate } from '../../app/api/generate/route.ts'
import { bearerHeader, jsonRequest } from '../helpers/http.mjs'
import { getTestState, resetTestState } from '../mocks/state.mjs'

const RELEVANT_ENV_KEYS = [
  'GEMINI_API_KEY',
  'GEMINI_GENERATE_MODEL',
  'GENERATE_AI_PROVIDER',
]

function clearRelevantEnv() {
  for (const key of RELEVANT_ENV_KEYS) {
    delete process.env[key]
  }
}

beforeEach(() => {
  resetTestState()
  clearRelevantEnv()
})

describe('POST /api/generate Gemini request', () => {
  test('preserves Gemini request body parts for base64 and external image references', async () => {
    const state = getTestState()
    process.env.GEMINI_API_KEY = 'gm_test_key'
    process.env.GENERATE_AI_PROVIDER = 'gemini'
    const originalFetch = globalThis.fetch
    let capturedUrl = ''
    let capturedBody = null

    globalThis.fetch = async (url, init) => {
      capturedUrl = String(url)
      capturedBody = JSON.parse(init.body)

      return new Response(
        JSON.stringify({
          candidates: [
            {
              content: {
                parts: [
                  {
                    text: JSON.stringify({
                      items: [
                        { description: 'Pressure test and diagnostics', quantity: 1, unit_price: 95 },
                      ],
                      summary_note: 'Generated by Gemini',
                    }),
                  },
                ],
              },
            },
          ],
          usageMetadata: {
            promptTokenCount: 77,
            candidatesTokenCount: 21,
          },
        }),
        { status: 200, headers: { 'content-type': 'application/json' } }
      )
    }

    try {
      const request = jsonRequest('http://localhost/api/generate', {
        notes: 'diagnose low pressure',
        images: [
          'data:image/png;base64,QUJDRA==',
          'https://example.test/jobsite.jpg',
        ],
      }, {
        headers: bearerHeader(),
      })

      const response = await generateEstimate(request)
      const data = await response.json()

      assert.equal(response.status, 200)
      assert.equal(data.items[0].description, 'Pressure test and diagnostics')
      assert.match(capturedUrl, /gemini-2\.5-flash:generateContent/)
      assert.match(capturedUrl, /key=gm_test_key/)

      assert.match(capturedBody.systemInstruction.parts[0].text, /You are an expert North American Trade Estimator/)
      assert.equal(capturedBody.contents[0].role, 'user')
      assert.equal(capturedBody.contents[0].parts[0].text, 'Field Notes:\ndiagnose low pressure')
      assert.deepEqual(capturedBody.contents[0].parts[1], {
        inlineData: {
          mimeType: 'image/png',
          data: 'QUJDRA==',
        },
      })
      assert.equal(capturedBody.contents[0].parts[2].text, 'Reference image URL: https://example.test/jobsite.jpg')
      assert.equal(capturedBody.generationConfig.responseMimeType, 'application/json')
      assert.equal(capturedBody.generationConfig.temperature, 0.3)
      assert.equal(capturedBody.generationConfig.maxOutputTokens, 1500)
      assert.equal(state.openai.chatCalls.length, 0)
      assert.equal(state.usageQuota.recordCalls[0].input.promptTokens, 77)
      assert.equal(state.usageQuota.recordCalls[0].input.completionTokens, 21)
    } finally {
      globalThis.fetch = originalFetch
    }
  })
})
