export type EmailPlanTier = "free" | "starter" | "pro" | "team"

export interface EmailWatermarkOptions {
    planTier: EmailPlanTier
    referralUrl?: string
    appUrl?: string
    businessName?: string
    quotesUsed?: number
}

const DEFAULT_APP_URL = "https://snapquote.app"

function escapeHtml(value: string): string {
    return value
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;")
        .replace(/'/g, "&#39;")
}

function normalizeHttpUrl(value: string | undefined, fallback: string): string {
    const candidate = value?.trim() || fallback

    try {
        const parsed = new URL(candidate)
        if (parsed.protocol === "http:" || parsed.protocol === "https:") {
            return parsed.toString()
        }
    } catch {}

    return fallback
}

function normalizeOptionalHttpUrl(value: string | undefined): string {
    const candidate = value?.trim() || ""
    if (!candidate) return ""

    try {
        const parsed = new URL(candidate)
        if (parsed.protocol === "http:" || parsed.protocol === "https:") {
            return parsed.toString()
        }
    } catch {}

    return ""
}

function buildFreeWatermarkHtml(appUrl: string, referralUrl: string): string {
    const safeAppUrl = escapeHtml(appUrl)
    const safeReferralUrl = escapeHtml(referralUrl)

    return `
<div style="margin-top:24px;padding:16px 18px;background:#f0f4ff;border-top:2px solid #2563eb;border-radius:0 0 10px 10px;font-family:Arial,sans-serif;">
    <p style="margin:0;font-size:14px;font-weight:600;color:#111827;">
        Made with <a href="${safeAppUrl}" target="_blank" rel="noopener noreferrer" style="color:#2563eb;text-decoration:none;">SnapQuote</a>
    </p>
    <p style="margin:8px 0 0;font-size:13px;line-height:1.5;color:#475569;">
        Speak your job — get a professional estimate in 30 seconds
    </p>
    ${safeReferralUrl ? `<p style="margin:10px 0 0;"><a href="${safeReferralUrl}" target="_blank" rel="noopener noreferrer" style="font-size:13px;font-weight:600;color:#1d4ed8;text-decoration:none;">Try it free →</a></p>` : ""}
</div>`.trim()
}

function buildPaidWatermarkHtml(appUrl: string): string {
    const safeAppUrl = escapeHtml(appUrl)

    return `
<div style="margin-top:20px;font-family:Arial,sans-serif;font-size:11px;line-height:1.5;color:#9ca3af;">
    Powered by <a href="${safeAppUrl}" target="_blank" rel="noopener noreferrer" style="color:#9ca3af;text-decoration:none;">SnapQuote</a>
</div>`.trim()
}

export function hasFreeWatermarkExemption(quotesUsed: number): boolean {
    return quotesUsed < 5
}

export function buildEmailWatermarkHtml(options: EmailWatermarkOptions): string {
    const appUrl = normalizeHttpUrl(options.appUrl, DEFAULT_APP_URL)
    if (options.planTier !== "free") return buildPaidWatermarkHtml(appUrl)
    if (hasFreeWatermarkExemption(options.quotesUsed ?? 999)) {
        return buildPaidWatermarkHtml(appUrl)
    }

    const referralUrl = normalizeOptionalHttpUrl(options.referralUrl)
    return buildFreeWatermarkHtml(appUrl, referralUrl)
}

export function buildEmailFooterHtml(options: EmailWatermarkOptions): string {
    const appUrl = normalizeHttpUrl(options.appUrl, DEFAULT_APP_URL)
    const safeAppUrl = escapeHtml(appUrl)
    const safeName = escapeHtml(options.businessName?.trim() || "your contractor")

    return `
<div style="margin-top:16px;font-family:Arial,sans-serif;font-size:11px;line-height:1.5;color:#6b7280;">
    This estimate was generated by ${safeName} using <a href="${safeAppUrl}" target="_blank" rel="noopener noreferrer" style="color:#6b7280;text-decoration:none;">SnapQuote AI Estimator</a>.
</div>`.trim()
}
