export type EmailPlanTier = "free" | "starter" | "pro" | "team"

export interface EmailWatermarkOptions {
    planTier: EmailPlanTier
    referralUrl?: string
    appUrl?: string
    businessName?: string
    quotesUsed?: number
}

const DEFAULT_APP_URL = "https://snapquote.app"

function escapeHtml(value: string): string {
    return value
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;")
        .replace(/'/g, "&#39;")
}

function resolveAppUrl(appUrl?: string): string {
    const candidate = appUrl?.trim() || DEFAULT_APP_URL

    try {
        const url = new URL(candidate)
        if (url.protocol === "http:" || url.protocol === "https:") return url.toString()
    } catch {}

    return DEFAULT_APP_URL
}

function resolveReferralUrl(referralUrl?: string): string {
    const candidate = referralUrl?.trim() || ""
    if (!candidate) return ""

    try {
        const url = new URL(candidate)
        if (url.protocol === "http:" || url.protocol === "https:") return url.toString()
    } catch {}

    return ""
}

function resolveBusinessName(businessName?: string): string {
    const candidate = businessName?.trim() || ""
    return candidate ? escapeHtml(candidate) : "your business"
}

function buildFreePlanWatermarkHtml(appUrl: string, referralUrl: string): string {
    const callToActionHtml = referralUrl
        ? `
    <p style="margin:10px 0 0;">
        <a href="${escapeHtml(referralUrl)}" target="_blank" rel="noopener noreferrer" style="color:#2563eb;font-size:13px;font-weight:600;text-decoration:none;">Try it free →</a>
    </p>`
        : ""

    return `
<div style="margin-top:24px;padding:16px 18px;background:#f0f4ff;border-top:2px solid #2563eb;font-family:Arial,sans-serif;">
    <p style="margin:0;color:#111827;font-size:14px;font-weight:600;line-height:1.5;">
        Made with <a href="${escapeHtml(appUrl)}" target="_blank" rel="noopener noreferrer" style="color:#2563eb;text-decoration:none;">SnapQuote</a>
    </p>
    <p style="margin:8px 0 0;color:#475569;font-size:13px;line-height:1.5;">
        Speak your job — get a professional estimate in 30 seconds
    </p>${callToActionHtml}
</div>`.trim()
}

function buildPaidPlanWatermarkHtml(appUrl: string): string {
    return `
<div style="margin-top:20px;color:#9ca3af;font-family:Arial,sans-serif;font-size:11px;line-height:1.5;">
    Powered by <a href="${escapeHtml(appUrl)}" target="_blank" rel="noopener noreferrer" style="color:#9ca3af;text-decoration:none;">SnapQuote</a>
</div>`.trim()
}

export function hasFreeWatermarkExemption(quotesUsed: number): boolean {
    return quotesUsed < 5
}

export function buildEmailWatermarkHtml(options: EmailWatermarkOptions): string {
    const appUrl = resolveAppUrl(options.appUrl)

    if (options.planTier !== "free") {
        return buildPaidPlanWatermarkHtml(appUrl)
    }

    if (hasFreeWatermarkExemption(options.quotesUsed ?? 999)) {
        return buildPaidPlanWatermarkHtml(appUrl)
    }

    return buildFreePlanWatermarkHtml(appUrl, resolveReferralUrl(options.referralUrl))
}

export function buildEmailFooterHtml(options: EmailWatermarkOptions): string {
    const appUrl = resolveAppUrl(options.appUrl)
    const businessName = resolveBusinessName(options.businessName)

    return `
<div style="margin-top:16px;color:#6b7280;font-family:Arial,sans-serif;font-size:11px;line-height:1.5;">
    This estimate was generated by ${businessName} using <a href="${escapeHtml(appUrl)}" target="_blank" rel="noopener noreferrer" style="color:#6b7280;text-decoration:none;">SnapQuote AI Estimator</a>.
</div>`.trim()
}
