export const FREE_PLAN_GENERATE_LIMIT = 3
export const FREE_PLAN_TRANSCRIBE_LIMIT = 3
export const FREE_PLAN_SEND_EMAIL_LIMIT = 3
export const ANONYMOUS_GENERATE_LIMIT = 3

export const FREE_PLAN_MARKETING_QUOTE_LIMIT = FREE_PLAN_GENERATE_LIMIT
