#!/bin/bash

# 🔧 Orchestrator 5.1 — Hook Installer
# Usage: Run this from a CLIENT project's root directory.
#   bash /path/to/orchestrator/.agent/scripts/setup-hooks.sh
# Effect: Installs pre-push quality gate into the current project's .git/hooks.

BOLD="\033[1m"
GREEN="\033[32m"
YELLOW="\033[33m"
CYAN="\033[36m"
RED="\033[31m"
RESET="\033[0m"

HUB_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
TARGET_DIR=$(pwd)

echo ""
echo -e "${BOLD}${CYAN}🔧 ORCHESTRATOR 5.1 — HOOK INSTALLER${RESET}"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo -e "  Hub:    ${HUB_DIR}"
echo -e "  Target: ${TARGET_DIR}"
echo ""

# Check if this is a git repo
if [ ! -d "$TARGET_DIR/.git" ]; then
  echo -e "${RED}❌ Error: '$TARGET_DIR' is not a git repository.${RESET}"
  echo -e "${CYAN}   → Run 'git init' first, then re-run this script.${RESET}"
  exit 1
fi

# Check if pre-push.sh is accessible
PRE_PUSH_SCRIPT="$HUB_DIR/.agent/scripts/pre-push.sh"
if [ ! -f "$PRE_PUSH_SCRIPT" ]; then
  echo -e "${RED}❌ Error: pre-push.sh not found at Hub.${RESET}"
  exit 1
fi

# Create hooks directory if needed
mkdir -p "$TARGET_DIR/.git/hooks"

# Write the hook (calls the hub's pre-push script)
cat > "$TARGET_DIR/.git/hooks/pre-push" << HOOK
#!/bin/bash
# Auto-generated by Orchestrator 5.1 setup-hooks.sh
exec bash "${PRE_PUSH_SCRIPT}"
HOOK

chmod +x "$TARGET_DIR/.git/hooks/pre-push"

echo -e "${GREEN}✅ Pre-push quality gate installed successfully!${RESET}"
echo -e "   Hook: ${TARGET_DIR}/.git/hooks/pre-push"
echo -e "   Gate: ${PRE_PUSH_SCRIPT}"
echo ""
echo -e "${CYAN}  Every 'git push' in this project will now run the quality gate.${RESET}"
echo ""


BOLD="\033[1m"
GREEN="\033[32m"
YELLOW="\033[33m"
CYAN="\033[36m"
RED="\033[31m"
RESET="\033[0m"

# PROJECTS list removed to avoid stale hardcoded paths.
# Focus on installing hook to the current TARGET_DIR.


echo ""
echo -e "${BOLD}${CYAN}🔧 ORCHESTRATOR 4.0 — HOOK INSTALLER${RESET}"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo ""

installed=0
skipped=0

# Install to TARGET_DIR (Current working directory)
name=$(basename "$TARGET_DIR")

# Check if pre-push script exists in hub
if [ ! -f "$PRE_PUSH_SCRIPT" ]; then
  echo -e "  ${RED}❌ Error: pre-push.sh not found at $PRE_PUSH_SCRIPT${RESET}"
  exit 1
fi

# Create hooks directory if needed
mkdir -p "$TARGET_DIR/.git/hooks"

# Create the hook (wrapper that calls the hub's script)
cat > "$TARGET_DIR/.git/hooks/pre-push" << HOOK
#!/bin/bash
# Auto-generated by Orchestrator 5.1 setup-hooks.sh
exec bash "${PRE_PUSH_SCRIPT}"
HOOK

chmod +x "$TARGET_DIR/.git/hooks/pre-push"
echo -e "  ${GREEN}✅ ${name}: hook installed${RESET}"
installed=1


echo ""
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo -e "  ${GREEN}✅ ${installed} installed${RESET}  ${YELLOW}⚠️  ${skipped} skipped${RESET}"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo ""
